fixed FTP client hangs on I/O exceptions during read, write, and list…
Guichaguri/MinimalFTP pull request #20
Opened 2024-11-26 07:45 UTC by kaungkhantjc

First of all, thank you so much for this amazing library. 🎉

- fixed: FTP client hangs on I/O exceptions during read, write, and list

When I/O exceptions occurred, FTP clients hangs. For example: 

```java
con.sendResponse(150, "Receiving a file stream for " + path);
receiveStream(fs.writeFile(file, start));
```

`writeFile` may throws IOException due to starting FTP server as read-only or other reasons. So, early sending of `150` code can hangs FTP clients **if IOException occurred** like this.

![FTP_hangs_on_IO_exception](https://github.com/user-attachments/assets/defeaf34-7296-4eed-8eb5-9c93e458dc4f)

So I fixed it by calling this method first before sending response like this.

```java
OutputStream fileStream = fs.writeFile(file, start);
con.sendResponse(150, "Receiving a file stream for " + path);
receiveStream(fileStream);
```

And here are the expected and working results when IOException occurred.

| Windows Explorer |  [Material Files](https://github.com/zhanghai/MaterialFiles) |
:-------------------------:|:-------------------------:
![FTP_write_permission_denied_pc](https://github.com/user-attachments/assets/a5ea9c07-bcf4-4850-9380-fee2fa0ee042) | ![FTP_write_permission_denied_android](https://github.com/user-attachments/assets/51c69d4b-c441-4c07-a092-a030fc05c17f)

Similar issues like reading and listing files are also fixed.

- implemented read-only file system support with backward compatibility for Java 7

Read only file system is optional because we can simply implement this feature by extending `NativeFileSystem` class.
But for Android, `Files.walk()` method requires API level 26 in Android. For compatibility with older versions (Java 7), I used 	`file.listFiles()` instead.

2025-01-12 19:47 UTC, Guichaguri commented
Thank you! I left two comments, but other than those everything looks good :)

2025-01-13 01:58 UTC, kaungkhantjc commented
Thank you for the review! I'm new to pull request reviews, and I wasn't able to find any comments in the [Files changed](https://github.com/Guichaguri/MinimalFTP/pull/20/files) tab. Could you kindly guide me on where to look or clarify if I missed something?

2025-01-16 01:01 UTC, Guichaguri requested changes

2025-01-16 01:01 UTC, Guichaguri commented on src/main/java/com/guichaguri/minimalftp/impl/NativeFileSystemCompat.java
> +            throw new IOException("Couldn't delete file: " + file.getAbsolutePath());
Instead of creating a new class for improving the compatibility with older Android API levels, how about implementing these changes directly to the `NativeFileSystem`?

2025-01-16 01:01 UTC, Guichaguri commented on src/main/java/com/guichaguri/minimalftp/handler/FileHandler.java
> +        Object[] files = fs.listFiles(dir);
I think this check should be implemented directly in `NativeFileSystem`, which should check null and return either an empty array, or throw an IOException instead. What do you think?

2025-01-16 01:02 UTC, Guichaguri commented
Sorry, my bad! I forgot to click to submit the review

2025-01-16 05:15 UTC, kaungkhantjc commented on src/main/java/com/guichaguri/minimalftp/impl/NativeFileSystemCompat.java
> +            throw new IOException("Couldn't delete file: " + file.getAbsolutePath());
It would be a great option. 
But, as of this writing, Android apps with a minimum SDK of 26 (Android 8.0) will run on approximately 95.4% of devices, and major Android versions are generally released once per year. So, I think the `NativeFileSystem` class is already perfect, and we just need to use a compatibility class **only** if we need to support older systems (Java 7). Anyway, compatibility issue is just one, so I think the choice is yours.

2025-01-16 05:25 UTC, kaungkhantjc commented on src/main/java/com/guichaguri/minimalftp/handler/FileHandler.java
> +        Object[] files = fs.listFiles(dir);
In Java, every object reference is `nullable` by default, except for primitive data types.

If we expect data returned from `listFiles()` method to be **non-null**, I think we should use an annotation like `@NotNull` or `@NonNull` in `IFileSystem` class. It can raise awareness to the user implementing this class.

```java
@NotNull F[] listFiles(F dir) throws IOException;
```

When we override this annotated method, IDEs will generate like this.

```java
@Override
public @NotNull File[] listFiles(File dir) throws IOException {
}
```

Generally, there are well-known annotations for that like Jetbrains annotations for **Intellij** or androidx for **Android Studio**, etc ..

"org.jetbrains:annotations:23.0.0"
"androidx.annotation:annotation:1.9.1"

But there is a tiny problem. In Intellij IDE, jetbrain annotation shows static code check for non-null. In Android Studio IDE, androidx annotation shows static code check like this.

![Screenshot 2025-01-16 112838](https://github.com/user-attachments/assets/cd856a91-ed7d-4408-91a0-561d713665cd)

No static code check is shown if we use one annotation in the other IDE. So, I think we have 2 options.

1. Just ignore that tiny problem and use desired annotation (or even custom annotation)
2. Just let the **Java** be **Java** (allow nullable data return) and let the `FileHandler` handle null values. I think we should prefer this one because "for" loop definitely needs non null value.

2025-01-17 03:59 UTC, Guichaguri commented on src/main/java/com/guichaguri/minimalftp/handler/FileHandler.java
> +        Object[] files = fs.listFiles(dir);
I totally agree with adding the annotations. About deciding which one to pick, what do you think about the `javax.annotation.Nonnull`? AFAIK that works on IntelliJ, I don't know if it also works on Android Studio or if it even exists in the Android SDK

I think exceptions are the way to go since most other methods already use them for invalid operations, because of that, I don't think adding a second way of declaring errors (returning null) is a good design choice.

2025-01-17 04:10 UTC, Guichaguri commented on src/main/java/com/guichaguri/minimalftp/impl/NativeFileSystemCompat.java
> +            throw new IOException("Couldn't delete file: " + file.getAbsolutePath());
I don't like having two different classes that do pretty much the same thing without any specific reason to pick the `NativeFileSystem` over the `NativeFileSystemCompat`, since the compat one would work everywhere. I think that would only create some confusion around which one to use.

We should either remove that implementation from the library, making that part of your own project, or move that `delete` implementation into `NativeFileSystem`. What do you think?

2025-01-17 06:36 UTC, kaungkhantjc commented on src/main/java/com/guichaguri/minimalftp/impl/NativeFileSystemCompat.java
> +            throw new IOException("Couldn't delete file: " + file.getAbsolutePath());
You're right, it's cleaner to have a single implementation. I think we should remove this implementation and drop support for legacy systems (keep `delete` implementation as original). This also follows Google's lead with androidx libraries, which drop support for older SDKs in every new major release. We can still support legacy systems in our own project by extending `NativeFileSystem`.

2025-01-17 06:43 UTC, kaungkhantjc commented on src/main/java/com/guichaguri/minimalftp/handler/FileHandler.java
> +        Object[] files = fs.listFiles(dir);
It's a good point.
`javax.annotation.Nonnull` also works on Android Studio (I tested it with `com.google.code.findbugs:jsr305:3.0.2` lib and it can show static code check too). 

Thank you so much for your patient review. I will create a new commit with the following changes.
- Revert "implemented read-only file system support with backward compatibility for Java 7"
- Revert "fixed FTP client hangs on I/O exceptions during read, write, and list operations."
- fixed FTP client hangs on I/O exceptions during read, write, and list operations (without null checks)

For annotations, can you please add them later? Or I will do it later with a new pull request. Right now, I cannot build this project directly due to Gradle issues (I think it is from my side; ISPs from my country ban random websites).

2025-01-18 07:11 UTC, Guichaguri approved these changes
Thank you! I really appreciate it 😄

2025-01-18 07:11 UTC, merged